spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: wsharkcoder
    password: wsharkcoder
    url: jdbc:mysql://localhost:3306/marcket?characterEncoding=utf-8&useSSL=false
